# Generated by Django 3.1.1 on 2022-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_District',
            fields=[
                ('district_code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='District Code')),
                ('district_name', models.CharField(max_length=30, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='Register_SRO',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('sro_code', models.CharField(max_length=30, verbose_name='SRO Code')),
                ('sro_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='SRO ID')),
                ('sro_name', models.CharField(max_length=30, verbose_name='SRO Name')),
            ],
        ),
        migrations.CreateModel(
            name='Register_Village',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('sro_code', models.CharField(max_length=30, verbose_name='SRO Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('village_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Village ID')),
                ('village_name', models.CharField(max_length=30, verbose_name='Village Name')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Claiment',
            fields=[
                ('claiment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Claiment ID')),
                ('gsws_id', models.IntegerField(verbose_name='GSWS ID')),
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('gsws_code', models.CharField(max_length=30, verbose_name='GSWS Code')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('claiment_name', models.CharField(max_length=30, verbose_name='Claiment Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('aadhar', models.CharField(max_length=16, verbose_name='Aadhar No.')),
                ('relation_of', models.CharField(max_length=30, verbose_name='Relation To')),
                ('relation_name', models.CharField(max_length=30, verbose_name='Relation Name')),
                ('village_id', models.IntegerField(verbose_name='Village ID')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('door_no', models.CharField(max_length=30, verbose_name='Door No.')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone No.')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_District',
            fields=[
                ('district_code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='District Code')),
                ('district_name', models.CharField(max_length=30, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_GSWS',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('gsws_code', models.CharField(max_length=30, verbose_name='GSWS Code')),
                ('gsws_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='GSWS ID')),
                ('GSWS_name', models.CharField(max_length=30, verbose_name='GSWS Name')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Mandal',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('mandal_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mandal ID')),
                ('mandal_name', models.CharField(max_length=30, verbose_name='Mandal Name')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_Village',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('village_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Village ID')),
                ('village_name', models.CharField(max_length=30, verbose_name='Village Name')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_VRO',
            fields=[
                ('vro_entry', models.AutoField(primary_key=True, serialize=False, verbose_name='VRO Entry')),
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('gsws_code', models.CharField(max_length=30, verbose_name='GSWS Code')),
                ('vro_code', models.CharField(max_length=30, verbose_name='VRO code')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_VRO_Details',
            fields=[
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('vro_code', models.CharField(max_length=30, verbose_name='VRO code')),
                ('vro_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='VRO ID')),
                ('VRO_name', models.CharField(max_length=30, verbose_name='VRO Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('aadhar', models.CharField(max_length=16, verbose_name='Aadhar No.')),
                ('relation_of', models.CharField(max_length=30, verbose_name='Relation To')),
                ('relation_name', models.CharField(max_length=30, verbose_name='Relation Name')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('village_name', models.CharField(max_length=30, verbose_name='Village Name')),
                ('door_no', models.CharField(max_length=30, verbose_name='Door No.')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone No.')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Date')),
            ],
        ),
        migrations.CreateModel(
            name='Shedule_Entry',
            fields=[
                ('claiment_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Claiment ID')),
                ('gsws_id', models.IntegerField(verbose_name='GSWS ID')),
                ('village_id', models.IntegerField(verbose_name='Village ID')),
                ('district_code', models.CharField(max_length=30, verbose_name='District Code')),
                ('mandal_code', models.CharField(max_length=30, verbose_name='Mandal Code')),
                ('village_code', models.CharField(max_length=30, verbose_name='Village Code')),
                ('gsws_code', models.CharField(max_length=30, verbose_name='GSWS Code')),
                ('old_house_no', models.CharField(max_length=30, verbose_name='Phone No.')),
                ('nature_use', models.IntegerField(verbose_name='Nature Use')),
                ('plot_no', models.IntegerField(verbose_name='Plot No.')),
                ('schedule_no', models.IntegerField(verbose_name='Schedule No.')),
                ('jurisdicition', models.IntegerField(verbose_name='Jurisdicition')),
                ('ward_no', models.IntegerField(verbose_name='Ward No.')),
                ('block_no', models.IntegerField(verbose_name='Block No.')),
                ('survey_no', models.CharField(max_length=30, verbose_name='Survey No')),
                ('east_eng', models.CharField(max_length=30, verbose_name='East Eng')),
                ('west_eng', models.CharField(max_length=30, verbose_name='West Eng')),
                ('north_eng', models.CharField(max_length=30, verbose_name='North Eng')),
                ('south_eng', models.CharField(max_length=30, verbose_name='South Eng')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Date')),
            ],
        ),
    ]
