# Generated by Django 3.1.1 on 2022-07-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shedule_Entry',
            new_name='Schedule_Entry',
        ),
    ]
